# Generated by Django 5.2.5 on 2025-08-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_character_description_embedding'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='teams', through='teams.TeamMember', to='characters.character'),
        ),
    ]
