# Generated by Django 5.2.5 on 2025-09-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
