# Generated by Django 5.2.5 on 2025-08-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='biography',
            field=models.TextField(blank=True, help_text='AI-generated biography of the character.', null=True),
        ),
    ]
