# Generated by Django 5.2.5 on 2025-08-23 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='evilness_explanation',
            field=models.TextField(blank=True, help_text='Explanation of the evilness score by AI.', null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='evilness_score',
            field=models.IntegerField(blank=True, db_index=True, help_text='Evilness score from 0 to 100 generated by AI, where 0 is good and 100 is evil.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='character',
            name='is_evil',
            field=models.BooleanField(db_index=True, default=False, help_text='Classification by AI if the character is evil.'),
        ),
    ]
