# Generated by Django 5.2.5 on 2025-08-23 18:25

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_character_evilness_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='description_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='Vector embedding for semantic search.', null=True),
        ),
    ]
